# Generated by Django 3.1.1 on 2020-11-24 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todo',
            new_name='todoList',
        ),
    ]
