# Generated by Django 3.1.1 on 2020-10-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobready', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fresherquestion',
            name='Category',
            field=models.CharField(choices=[('J', 'Java'), ('C', 'C'), ('PHP', 'PHP')], default='NA', max_length=5),
        ),
    ]
