# Generated by Django 3.1.1 on 2020-10-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobready', '0002_fresherquestion_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fresherquestion',
            name='Category',
            field=models.CharField(choices=[('J', 'Java'), ('C', 'C'), ('PHP', 'PHP'), ('Py', 'Pyhton')], default='NA', max_length=5),
        ),
    ]
